version: '3'

services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
      args:
        - bucketName=http4kbox
    ports:
      - "80:80"
  http4kbox:
    container_name: http4kbox
    image: daviddenton/http4kbox-native
    ports:
      - "10000:10000"
    links:
       - proxy
    env_file:
        - http4kbox.env
